### ISSUE TITLE
create helpers for the response

### ISSUE THREAD

**Issue by rishabhborn2win** [gdscnitp/charges-by-tenant#10]
Proper layout of the success and error response should be created so that these helpers can be used to respond for each route

**Comment by SihotiyaKartik** [comment]
can you please elaborate more about this issue!
![Screenshot (237)](https://user-images.githubusercontent.com/66414027/142764950-e10e06c3-5dd3-4039-9e63-85d535d20551.png)
This type of code will work??

**Comment by rishabhborn2win** [comment]
![WhatsApp Image 2021-11-30 at 9 57 51 AM](https://user-images.githubusercontent.com/55771529/143987756-79d9e72f-58cd-4df6-8d3e-3ed2dd6bf6c0.jpeg)

Take the reference from this code snippet.
